---
version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.22
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.40.0
    volumes:
      - ./otel_collector_local.yaml:/etc/otel/config.yaml
    ports:
      - "1888:1888"    # pprof extension
      - "8888:8888"    # Prometheus metrics exposed by the collector
      - "8889:8889"    # Prometheus exporter metrics
      - "13133:13133"  # health_check extension
      - "4317:4317"    # OTLP gRPC receiver
      - "55670:55679"  # zpages extension
    environment:
      - DD_API_KEY
      - DD_SERVICE
      - DD_ENV
    depends_on:
      - jaeger-all-in-one

  # Datadog Agent
  dd-agent:
    image: datadog/agent:7.29.1
    ports:
      - "8126:8126"
    environment:
      - DD_API_KEY
      - DD_SERVICE
      - DD_ENV
      - DD_APM_ENABLED=false
      - DD_PROCESS_AGENT_ENABLED=false
