receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 10s

exporters:
  datadog/api:
    traces:
      ignore_resources: ["GET /ping"]
      span_name_remappings:
        go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp.server: otelhttp.server
        go.opentelemetry.io_contrib_instrumentation_net_http_otelhttp.client: otelhttp.client

  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api,jaeger]
