# Copyright The Linux Foundation and each contributor.
# SPDX-License-Identifier: MIT
---
name: Publish

'on':
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@v0.8
        with:
          version: v0.18.0
      - run: |
          ko build . \
            --bare \
            --platform linux/amd64,linux/arm64 \
            -t latest -t ${{ github.sha }} \
            --sbom spdx
