# Copyright The Linux Foundation and each contributor.
# SPDX-License-Identifier: MIT
---
name: Publish

'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.6
      - run: |
          ko build --bare --platform linux/amd64,linux/arm64 -t latest -t ${{ github.sha }} --sbom spdx .
